title       = "speedrun"
baseURL     = "https://speedrun-cli.tamnd.com/"
description = "A command line for speedrun."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/speedrun-cli"
